require: rubocop-rspec

AllCops:
  Exclude:
    - 'bin/*'
    - 'puppet/**/*'
    - 'vendor/bundle/**/*'

RSpec/DescribeClass:
  Exclude:
    - 'spec/api/*'

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Enabled: false
